language: python

sudo: false

python:
  - "2.7"

services:
  - mysql
  - postgresql

addons:
  apt:
    packages:
      # FIXME: when activating the services above I don't think these are needed.
      - odbcinst1debian2
      - odbcinst
      - tdsodbc
      - e2fsprogs
      # FIXME: the dependencies below can probably be replaced by conda.
      - libc6
      - freetds-dev
      - freetds-bin
      - unixodbc
      - unixodbc-dev
      - mysql-client
      # FIXME: I don't see the need for these anywhere.
      - cmake
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev

before_script:
  - ./ci-helpers/mysql_setup.sh
  - ./ci-helpers/postgres_setup.sh
  - ./ci-helpers/travis/freetds.sh


before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes --all
    - conda config --add channels odm2 --force
    - conda create --yes -n TEST python=$TRAVIS_PYTHON_VERSION --file requirements.txt --file requirements-dev.txt
    - source activate TEST

install:
  - sudo pip  install -e git+https://github.com/ODM2/geoalchemy.git@v0.7.4#egg=geoalchemy-0.7.4
  - python -m pip install   .
  - python -m pip install  -r requirements_tests.txt  --allow-external pyodbc --allow-unverified pyodbc
  - pip list

script:
  - py.test
