language: python

sudo: false

python:
  - "2.7"

services:
  - mysql
  - postgresql

addons:
  apt:
    packages:
      - cmake
      - unixodbc
      - unixodbc-dev
      - odbcinst1debian2
      - odbcinst
      - freetds-dev
      - freetds-bin
      - tdsodbc
      - libc6
      - e2fsprogs
      - mysql-client
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev

before_script:
  - ./ci-helpers/mysql_setup.sh
  - ./ci-helpers/postgres_setup.sh
  - ./ci-helpers/travis/freetds.sh


before_install:
  - sudo pip install --upgrade pip
  - sudo python -m pip install pandas
  - export PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=1;sudo python -m  pip install pymssql

install:
  - sudo pip  install -e git+https://github.com/ODM2/geoalchemy.git@v0.7.4#egg=geoalchemy-0.7.4
  - python -m pip install   .
  - python -m pip install  -r requirements_tests.txt  --allow-external pyodbc --allow-unverified pyodbc
  - pip list

script:
  - py.test
